//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindergartenDesktopApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildDocument
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public byte[] FileBytes { get; set; }
        public int ChildId { get; set; }
    
        public virtual Child Child { get; set; }
    }
}
