//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindergartenDesktopApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildRelative
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> Year { get; set; }
        public int ChildId { get; set; }
        public int RelativeRoleId { get; set; }
    
        public virtual Child Child { get; set; }
        public virtual RelativeRole RelativeRole { get; set; }
    }
}
